import React, { useEffect } from 'react';

const Custom = () => {
  useEffect(() => {
    const foo = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi atque magni necessitatibus obcaecati quas quod voluptate! Animi, reiciendis soluta? Aspernatur autem consequatur corporis delectus dolore fugiat itaque labore saepe tempora';
    const baz = foo.substr(10, 20);
    console.log(baz);
  }, []);
  return /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement("p", null, "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi consequatur eius expedita nihil numquam obcaecati similique suscipit veritatis? Aliquam atque distinctio dolore ex excepturi explicabo facilis impedit laboriosam tempore voluptatibus."), /*#__PURE__*/React.createElement("p", null, "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi atque magni necessitatibus obcaecati quas quod voluptate! Animi, reiciendis soluta? Aspernatur autem consequatur corporis delectus dolore fugiat itaque labore saepe tempora."), /*#__PURE__*/React.createElement("p", null, "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi atque magni necessitatibus obcaecati quas quod voluptate! Animi, reiciendis soluta? Aspernatur autem consequatur corporis delectus dolore fugiat itaque labore saepe tempora."), /*#__PURE__*/React.createElement("p", null, "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi atque magni necessitatibus obcaecati quas quod voluptate! Animi, reiciendis soluta? Aspernatur autem consequatur corporis delectus dolore fugiat itaque labore saepe tempora."), /*#__PURE__*/React.createElement("p", null, "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi atque magni necessitatibus obcaecati quas quod voluptate! Animi, reiciendis soluta? Aspernatur autem consequatur corporis delectus dolore fugiat itaque labore saepe tempora."), /*#__PURE__*/React.createElement("p", null, "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi atque magni necessitatibus obcaecati quas quod voluptate! Animi, reiciendis soluta? Aspernatur autem consequatur corporis delectus dolore fugiat itaque labore saepe tempora."));
};

export default Custom;